### ISSUE TITLE
可以升级到10.13么

### ISSUE THREAD

**Issue by mac-zhou** [mygoare/Hackintosh#1]
hi，请问可以升级到10.13了么？

**Comment by mygoare** [comment]
我目前还一直用着10.12，还没有折腾10.13，你可以参考学习下 https://www.tonymacx86.com， 以我的经验，如果你机器黑苹果完美成功过，装后续的版本基本问题不大

升级前备份好所有个人资料

**Comment by 0xbw** [comment]
好的 感谢
