### ISSUE TITLE
笔记本真的只能使用集成显卡吗？集成显卡能支持4K显示器吗？

### ISSUE THREAD

**Issue by guochunxing** [mygoare/Hackintosh#2]

**Comment by mygoare** [comment]
有独显的笔记本 应该是可以 找到相应的驱动的，我只弄过 n卡 的。

我大部分折腾的都是台式机，台式机的n卡 是可以找到驱动的，
你google  hackintosh web driver nvidia 可以找到，
https://www.insanelymac.com/forum/topic/324195-nvidia-web-driver-updates-for-macos-high-sierra-update-11032018/ 这是 high sierra 的

我台式机 n卡 装上驱动 是可以 4k分辨率的， 集成显卡要看它本身支不支持

希望可以帮到你
