### ISSUE TITLE
Z97M-D3H有升级到Big Sur或者Monterey的计划吗？

### ISSUE THREAD

**Issue by chujiezheng** [mygoare/Hackintosh#9]

**Comment by mygoare** [comment]
你可以参看opencore 的官网，一步一步的下来，我已经成功安装 big sur 了， 耐心点，慢慢来

这是我的台式机EFI：
https://github.com/mygoare/hackintosh/tree/master/11.6.1

**Comment by chujiezheng** [comment]
多谢建议~
我已经参照网上的教程把我的台式机顺利升到了Monterey，主要步骤是：
- 定制usb
- 更新驱动
- 更新opencore和config.plist文件
